name: BitcoinMedal
version: 0.11.1.0
summary: "BitcoinMedal: the secure, private, untraceable cryptocurrency https://BitcoinMedal.com"
description: |
    BitcoinMedal is a private, secure, untraceable, decentralised digital currency.
    You are your bank, you control your funds, and nobody can trace your transfers
    unless you allow them to do so.
grade: devel
confinement: strict

apps:
    BitcoinMedald:
        daemon: forking
        command: |
          BitcoinMedald-wrapper --detach --data-dir ${SNAP_COMMON} --config-file ${SNAP_USER_DATA}/etc/BitcoinMedald.conf
        plugs:
            - network
            - network-bind
    BitcoinMedal-wallet-rpc:
        command: |
          BitcoinMedal-wallet-rpc --log-file ${SNAP_USER_DATA}
        plugs:
            - home
            - network
            - network-bind
    BitcoinMedal-wallet-cli:
        command: |
          BitcoinMedal-wallet-cli --log-file ${SNAP_USER_DATA}
        plugs:
            - home
            - network

parts:
    cmake-build:
        plugin: cmake
        configflags:
            - -DBDB_STATIC=1
            - -DUPNP_STATIC=1
            - -DBoost_USE_STATIC_LIBS=1
            - -DBoost_USE_STATIC_RUNTIME=1
            - -DARCH=default
        source: .
        build-packages:
            - gcc
            - pkg-config
            - libunbound-dev
            - libevent-dev
            - libboost-all-dev
            - libdb-dev
            - libunwind-dev
            - libminiupnpc-dev
            - libldns-dev
            - libexpat1-dev
            - bison
            - doxygen
            - graphviz
        stage-packages:
            - libminiupnpc10
            - libunbound2
            - libunwind8
        prime:
            - bin
            - usr/lib/
            - -usr/lib/gcc
            - -usr/share

    dist-files:
        plugin: dump
        source: .
        organize:
            contrib/snap/BitcoinMedald.conf: etc/BitcoinMedald.conf
            contrib/snap/BitcoinMedald-wrapper: bin/BitcoinMedald-wrapper
        prime:
            - etc
            - bin
